# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/spaka/AppData/Local/Temp/toggle_windowphTFWN.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1030, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1349, 900))
        MainWindow.setStyleSheet("Background-color: rgb(45, 45, 45)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background: rgb(35, 35, 35)")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_toggle.sizePolicy().hasHeightForWidth())
        self.frame_toggle.setSizePolicy(sizePolicy)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color:rgb(0, 47, 215)")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_toggle)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_toggle)
        self.btn_toggle.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_toggle.setStyleSheet("border: 0px solid;\n"
"")
        self.btn_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/1200px-Delhi_Metro_logo.svg_copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_toggle.setIcon(icon)
        self.btn_toggle.setObjectName("btn_toggle")
        self.horizontalLayout_3.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setStyleSheet("background-image: url(:/backgroundim.jpeg);\n"
"background-position: center;\n"
"  background-repeat: no-repeat;\n"
"\n"
"")
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background:rgb(35, 35, 35)")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menu = QtWidgets.QFrame(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top_menu.sizePolicy().hasHeightForWidth())
        self.frame_top_menu.setSizePolicy(sizePolicy)
        self.frame_top_menu.setMinimumSize(QtCore.QSize(70, 150))
        self.frame_top_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menu.setObjectName("frame_top_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_top_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_page_1 = QtWidgets.QPushButton(self.frame_top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_page_1.sizePolicy().hasHeightForWidth())
        self.Btn_page_1.setSizePolicy(sizePolicy)
        self.Btn_page_1.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_page_1.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.Btn_page_1.setFont(font)
        self.Btn_page_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_page_1.setStyleSheet("QPushButton{\n"
" background-color: rgb(35, 35, 35);\n"
" border: 0px solid;\n"
" color: rgb(39, 84, 244)\n"
"}\n"
"QPushButton:hover{\n"
" background-color:rgb(59, 100, 234);\n"
" border: 0px solid;\n"
" color:rgb(45, 45, 45);\n"
"}")
        self.Btn_page_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/location_copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Btn_page_1.setIcon(icon1)
        self.Btn_page_1.setIconSize(QtCore.QSize(16, 16))
        self.Btn_page_1.setObjectName("Btn_page_1")
        self.verticalLayout_2.addWidget(self.Btn_page_1)
        self.Btn_page_2 = QtWidgets.QPushButton(self.frame_top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_page_2.sizePolicy().hasHeightForWidth())
        self.Btn_page_2.setSizePolicy(sizePolicy)
        self.Btn_page_2.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_page_2.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.Btn_page_2.setFont(font)
        self.Btn_page_2.setStyleSheet("QPushButton{\n"
" background-color: rgb(35, 35, 35);\n"
" border: 0px solid;\n"
" color: rgb(39, 84, 244)\n"
"}\n"
"QPushButton:hover{\n"
" background-color:rgb(59, 100, 234);\n"
" border: 0px solid;\n"
" color:rgb(45, 45, 45);\n"
"}")
        self.Btn_page_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/t.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Btn_page_2.setIcon(icon2)
        self.Btn_page_2.setIconSize(QtCore.QSize(16, 16))
        self.Btn_page_2.setObjectName("Btn_page_2")
        self.verticalLayout_2.addWidget(self.Btn_page_2)
        self.Btn_page_3 = QtWidgets.QPushButton(self.frame_top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_page_3.sizePolicy().hasHeightForWidth())
        self.Btn_page_3.setSizePolicy(sizePolicy)
        self.Btn_page_3.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_page_3.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.Btn_page_3.setFont(font)
        self.Btn_page_3.setStyleSheet("QPushButton{\n"
" background-color: rgb(35, 35, 35);\n"
" border: 0px solid;\n"
" color: rgb(39, 84, 244)\n"
"}\n"
"QPushButton:hover{\n"
" background-color:rgb(59, 100, 234);\n"
" border: 0px solid;\n"
" color:rgb(45, 45, 45);\n"
"}")
        self.Btn_page_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/white-down-arrow-milspe-bolts.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.Btn_page_3.setIcon(icon3)
        self.Btn_page_3.setObjectName("Btn_page_3")
        self.verticalLayout_2.addWidget(self.Btn_page_3)
        self.verticalLayout_3.addWidget(self.frame_top_menu, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setStyleSheet("")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        font = QtGui.QFont()
        font.setKerning(True)
        self.Pages_Widget.setFont(font)
        self.Pages_Widget.setMouseTracking(False)
        self.Pages_Widget.setAcceptDrops(False)
        self.Pages_Widget.setStyleSheet("")
        self.Pages_Widget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("")
        self.page_1.setObjectName("page_1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_9.setContentsMargins(220, 100, 250, 150)
        self.verticalLayout_9.setSpacing(7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.page_1)
        self.frame_3.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 375))
        self.frame_3.setStyleSheet("background: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(200, 40))
        self.label.setMaximumSize(QtCore.QSize(10000, 40))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"background : transparent\n"
"")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(200, 200))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 233))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setMouseTracking(True)
        self.frame.setStyleSheet("background : rgb(4, 44, 212)")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setContentsMargins(80, 11, 80, -1)
        self.verticalLayout_8.setSpacing(7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.comboBox_start = QtWidgets.QComboBox(self.frame)
        self.comboBox_start.setAutoFillBackground(False)
        self.comboBox_start.setStyleSheet("QComboBox {\n"
"    border: 0px 1px solid white;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(203,215,255);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color:transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-bottom-style: solid;\n"
"    border-color: rgb(93, 119, 229);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"\n"
"    /*border-left-width: 1px;\n"
"    border-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"\n"
"    border-bottom-width: 1px;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-style: solid;\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/white-down-arrow-milspe-bolts.png);\n"
"max-width: 10px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px transparent;\n"
"    selection-background-color:rgb(4, 44, 212);\n"
"    background-color: rgb(59, 100, 234);\n"
"    \n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background:rgb(59, 100, 234);\n"
"}\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color:rgb(59, 100, 234);      \n"
"     min-height: 5px;\n"
"     border-radius: 4px transparent;\n"
" }\n"
"  QComboBox QAbstractItemView::up-arrow:vertical,  QComboBox QAbstractItemView::down-arrow:vertical\n"
" {\n"
"image:url;\n"
"     background: none;\n"
"     border-radius: 4px transparent;\n"
" }\n"
"QComboBox QAbstractItemView::drop-down::down-arrow {image:url}\n"
" QScrollBar::sub-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::add-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QComboBox QAbstractItemView::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
" {\n"
"\n"
"     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QComboBox QAbstractItemView::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
" {\n"
"     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QComboBox QAbstractItemView::up-arrow:vertical,  QComboBox QAbstractItemView::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QComboBox QAbstractItemView::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }")
        self.comboBox_start.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox_start.setEditable(True)
        self.comboBox_start.setCurrentText("")
        self.comboBox_start.setMaxVisibleItems(4)
        self.comboBox_start.setFrame(False)
        self.comboBox_start.setObjectName("comboBox_start")
        self.verticalLayout_8.addWidget(self.comboBox_start)
        self.comboBox_end = QtWidgets.QComboBox(self.frame)
        self.comboBox_end.setStyleSheet("QComboBox {\n"
"    border: 0px 1px solid white;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(203,215,255);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color:transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-bottom-style: solid;\n"
"    border-color: rgb(93, 119, 229);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"\n"
"    /*border-left-width: 1px;\n"
"    border-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"\n"
"    border-bottom-width: 1px;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-style: solid;\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/white-down-arrow-milspe-bolts.png);\n"
"max-width: 10px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px transparent;\n"
"    selection-background-color:rgb(4, 44, 212);\n"
"    background-color: rgb(59, 100, 234);\n"
"    \n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background:rgb(59, 100, 234);\n"
"}\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color:rgb(59, 100, 234);      \n"
"     min-height: 5px;\n"
"     border-radius: 4px transparent;\n"
" }\n"
"  QComboBox QAbstractItemView::up-arrow:vertical,  QComboBox QAbstractItemView::down-arrow:vertical\n"
" {\n"
"image:url;\n"
"     background: none;\n"
"     border-radius: 4px transparent;\n"
" }\n"
"QComboBox QAbstractItemView::drop-down::down-arrow {image:url}\n"
" QScrollBar::sub-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::add-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QComboBox QAbstractItemView::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
" {\n"
"\n"
"     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QComboBox QAbstractItemView::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
" {\n"
"     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QComboBox QAbstractItemView::up-arrow:vertical,  QComboBox QAbstractItemView::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QComboBox QAbstractItemView::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }")
        self.comboBox_end.setEditable(True)
        self.comboBox_end.setFrame(False)
        self.comboBox_end.setObjectName("comboBox_end")
        self.verticalLayout_8.addWidget(self.comboBox_end)
        self.Btn_algorithm = QtWidgets.QPushButton(self.frame)
        self.Btn_algorithm.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.Btn_algorithm.setFont(font)
        self.Btn_algorithm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_algorithm.setAutoFillBackground(False)
        self.Btn_algorithm.setStyleSheet("QPushButton{\n"
" background-color:rgb(59, 100, 234);\n"
" border: 2px solid rgb(59, 100, 234);\n"
"border-color:rgb(59, 100, 234);\n"
"color:rgb(172, 184, 242); \n"
"}\n"
"QPushButton:hover{\n"
" background-color: rgb(124, 156, 252);\n"
" border: 0px solid;\n"
" color:rgb(45, 45, 45);\n"
"}")
        self.Btn_algorithm.setFlat(False)
        self.Btn_algorithm.setObjectName("Btn_algorithm")
        self.verticalLayout_8.addWidget(self.Btn_algorithm)
        self.verticalLayout_5.addWidget(self.frame)
        self.verticalLayout_9.addWidget(self.frame_3)
        self.Pages_Widget.addWidget(self.page_1)
        self.page_path = QtWidgets.QWidget()
        self.page_path.setObjectName("page_path")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_path)
        self.verticalLayout_10.setContentsMargins(50, -1, 50, 20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_4 = QtWidgets.QFrame(self.page_path)
        self.frame_4.setMinimumSize(QtCore.QSize(700, 181))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 181))
        self.frame_4.setStyleSheet("background:transparent\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(100, -1, 130, -1)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_start = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_start.sizePolicy().hasHeightForWidth())
        self.label_start.setSizePolicy(sizePolicy)
        self.label_start.setMinimumSize(QtCore.QSize(200, 40))
        self.label_start.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_start.setFont(font)
        self.label_start.setStyleSheet("QLabel{\n"
"margin-left: 10px; \n"
"border-radius: 20px;\n"
"border: 2px solid transparent; \n"
"background: transparent;\n"
"color: rgb(89, 118, 231);\n"
"}\n"
"QLabel:hover{\n"
"margin-left: 10px; \n"
"border: 2px solid rgb(10, 51, 217); \n"
"background:  rgb(10, 51, 217);\n"
"color: rgb(178, 192, 242);\n"
"}\n"
"")
        self.label_start.setFrameShape(QtWidgets.QFrame.Box)
        self.label_start.setAlignment(QtCore.Qt.AlignCenter)
        self.label_start.setObjectName("label_start")
        self.horizontalLayout_4.addWidget(self.label_start)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 5))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progressBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: transparent;\n"
"color: rgb(200, 200, 200);\n"
"border-style: none;\n"
"border-radius: 2px;\n"
"\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius: 2px;\n"
"background:qlineargradient(spread:repeat, x1:0, y1:0.511, x2:1, y2:0.506, stop:0 rgb(10, 51, 217), stop:1 #03ddff);\n"
"border: 0px;\n"
"}")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.label_end = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_end.sizePolicy().hasHeightForWidth())
        self.label_end.setSizePolicy(sizePolicy)
        self.label_end.setMinimumSize(QtCore.QSize(200, 40))
        self.label_end.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_end.setFont(font)
        self.label_end.setStyleSheet("QLabel{\n"
"margin-left: 10px; \n"
"border-radius: 20px;\n"
"border: 2px solid transparent; \n"
"background: transparent;\n"
"color: rgb(89, 118, 231);\n"
"}\n"
"QLabel:hover{\n"
"margin-left: 10px; \n"
"border: 2px solid rgb(10, 51, 217); \n"
"background:  rgb(10, 51, 217);\n"
"color: rgb(178, 192, 242);\n"
"}\n"
"")
        self.label_end.setAlignment(QtCore.Qt.AlignCenter)
        self.label_end.setObjectName("label_end")
        self.horizontalLayout_4.addWidget(self.label_end)
        self.progressBar.raise_()
        self.label_start.raise_()
        self.label_end.raise_()
        self.verticalLayout_10.addWidget(self.frame_4)
        self.tabWidget = QtWidgets.QTabWidget(self.page_path)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("\n"
"QTabWidget::pane { border: 0; }\n"
"QTabBar::tab {\n"
"  background: rgb(45, 45, 45);\n"
"  color: white; \n"
"border-radius:10px;\n"
"padding : 5px;\n"
"} \n"
"QTabBar::tab:selected {\n"
"  \n"
"    background-color: rgb(13, 13, 13);\n"
"  color: white; \n"
"padding : 5px;\n"
"} \n"
"QTabBar::tab:hover {\n"
"  background: rgb(94, 123, 233);\n"
"  color: white; \n"
"padding : 5px;\n"
"} ")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Route = QtWidgets.QWidget()
        self.Route.setObjectName("Route")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Route)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_2 = QtWidgets.QFrame(self.Route)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("background:rgb(35,35,35);\n"
"border-radius:50px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(40, 40, 40, 40)
        self.horizontalLayout_5.setSpacing(50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(362, 400))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_5.setStyleSheet("background: transparent;\n"
"border-radius:25px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 135))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 125))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_time = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(25)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("color:rgb(178, 192, 242);")
        self.label_time.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_time.setObjectName("label_time")
        self.verticalLayout_12.addWidget(self.label_time)
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(178, 192, 242);")
        self.label_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.verticalLayout_11.addWidget(self.frame_7)
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setMinimumSize(QtCore.QSize(340, 76))
        self.frame_10.setStyleSheet("background: rgb(10, 51, 217);\n"
"border-radius:0px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_changes = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_changes.setFont(font)
        self.label_changes.setStyleSheet("color:  rgb(203,215,255);")
        self.label_changes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_changes.setObjectName("label_changes")
        self.horizontalLayout_13.addWidget(self.label_changes)
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setStyleSheet("color:  rgb(124, 156, 248);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setStyleSheet("background: rgb(10, 51, 217);\n"
"border-radius:0px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_stops = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_stops.setFont(font)
        self.label_stops.setStyleSheet("color:  rgb(203,215,255);")
        self.label_stops.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stops.setObjectName("label_stops")
        self.horizontalLayout_7.addWidget(self.label_stops)
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(" color: rgb(124, 156, 248);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout_11.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setStyleSheet("background: rgb(10, 51, 217);\n"
"border-radius:0px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_cost = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_cost.setFont(font)
        self.label_cost.setStyleSheet("color:  rgb(203,215,255);")
        self.label_cost.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cost.setObjectName("label_cost")
        self.horizontalLayout_8.addWidget(self.label_cost)
        self.label_9 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(124, 156, 248);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.verticalLayout_11.addWidget(self.frame_8)
        self.horizontalLayout_5.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 478))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_6)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 478))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 478))
        self.scrollArea_2.setStyleSheet("\n"
" QScrollBar:vertical\n"
" {\n"
"     background-color: #2A2929;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color:rgb(55,55,55);      \n"
"     min-height: 5px;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::add-line:vertical\n"
" {\n"
"     margin: 3px 0px 3px 0px;\n"
"     border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
" {\n"
"\n"
"     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
" {\n"
"     border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"     height: 10px;\n"
"     width: 10px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 346, 478))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_15.addWidget(self.pushButton)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_6.addWidget(self.scrollArea_2)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.verticalLayout_13.addWidget(self.frame_2)
        self.tabWidget.addTab(self.Route, "")
        self.routemap = QtWidgets.QWidget()
        self.routemap.setObjectName("routemap")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.routemap)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_route_map = QtWidgets.QFrame(self.routemap)
        self.frame_route_map.setStyleSheet("background:rgb(35,35,35);\n"
"border-radius:50px;")
        self.frame_route_map.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_route_map.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_route_map.setObjectName("frame_route_map")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_route_map)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_4 = QtWidgets.QLabel(self.frame_route_map)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_16.addWidget(self.label_4)
        self.verticalLayout_14.addWidget(self.frame_route_map)
        self.tabWidget.addTab(self.routemap, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.Pages_Widget.addWidget(self.page_path)
        self.dynamically_labelling = QtWidgets.QWidget()
        self.dynamically_labelling.setObjectName("dynamically_labelling")
        self.Pages_Widget.addWidget(self.dynamically_labelling)
        self.page_trip_info = QtWidgets.QWidget()
        self.page_trip_info.setObjectName("page_trip_info")
        self.Pages_Widget.addWidget(self.page_trip_info)
        self.page_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.page_2.setFont(font)
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color : rgb(255, 255, 255)")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.Pages_Widget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_11 = QtWidgets.QFrame(self.page_3)
        self.frame_11.setStyleSheet("background: #232323;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_9.addWidget(self.frame_11)
        self.Pages_Widget.addWidget(self.page_3)
        self.verticalLayout_4.addWidget(self.Pages_Widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Pages_Widget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<strong>Select</strong> Station"))
        self.Btn_algorithm.setText(_translate("MainWindow", "Find Shortest Path"))
        self.label_start.setText(_translate("MainWindow", "<strong>TextLabel</strong>"))
        self.label_end.setText(_translate("MainWindow", "TextLabel"))
        self.label_time.setText(_translate("MainWindow", "<strong>53 mins</strong> to reach"))
        self.label_6.setText(_translate("MainWindow", "destination"))
        self.label_changes.setText(_translate("MainWindow", "<strong>3</strong> switches"))
        self.label_5.setText(_translate("MainWindow", "Line Changes"))
        self.label_stops.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">3 </span><span style=\" font-size:24pt;\">stops</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Number of Stops</p></body></html>"))
        self.label_cost.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Rs.</span><span style=\" font-size:24pt; font-weight:600;\"> 150</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Cost</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Route), _translate("MainWindow", "Route"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.routemap), _translate("MainWindow", "Route Map"))
import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

